### ISSUE TITLE
wmic spawn error

### ISSUE THREAD

**Issue by queckezz** [IndigoUnited/node-buffered-spawn#8]
Hey man, really cool project. I always get an error when running the following comand:

```bash
wmic logicaldisk where DeviceID="Z:" get freeSpace,size
```

using this simple script:

```js
const wmicArgs = [
  'freeSpace',
  'size'
].join(',')

spawn(
  'wmic',
  [
    'logicaldisk',
    'where',
    `DeviceID="Z:"`,
    'get',
    wmicArgs
  ]
).then(io => {
  console.log(io)
})
.catch(err => {
  console.log(err)
})
```

With `node-buffered-spawn` it gives me an error of `code: 'ECMDERR'` where as when executing it separately, it'll works as expected.

![04-04-_2016_16-01-17](https://cloud.githubusercontent.com/assets/2580598/14250423/ada45e30-fa7e-11e5-81ff-829fedf803e2.gif)
(excuse the german error, can't change that atm.)

Status code `2147749911` refers in the documentation to:
```js
WBEM_E_INVALID_QUERY
2147749911 (0x80041017)
Query was not syntactically valid.
```

**Comment by queckezz** [comment]
Just noticed, running the command with just one `wmicArgs` works as excepted.

```js
// works
spawn(
  'wmic',
  [
    'logicaldisk',
    'where',
    `DeviceID="C:"`,
    'get',
    'size'
  ]
)

// doesn't
spawn(
  'wmic',
  [
    'logicaldisk',
    'where',
    `DeviceID="C:"`,
    'get',
    'freeSpace,size'
  ]
)
```

**Comment by satazor** [comment]
Thanks for reporting this, I will look at it.

**Comment by satazor** [comment]
Last night I did some debugging and it seems that wmic is doing some weird parsing around quotes, see: http://stackoverflow.com/questions/23827199/escaping-strings-when-using-wmic

Though I am working on improving the escaping of arguments so that it only escapes and quotes when necessary. I will give you some news soon.

**Comment by satazor** [comment]
@queckezz should be fixed by https://github.com/IndigoUnited/node-cross-spawn-async/commit/26032206d9fc87105f5467a515ac6e4fed7cb1ba

I've released 3.1.0.

Please give me feedback if it works for you.

**Comment by queckezz** [comment]
Awesome, works perfectly fine now! Thanks for the fast replies and the fix.

**Comment by satazor** [comment]
<3

**Comment by satazor** [comment]
@queckezz I had to revert the change made in `cross-spawn-async` because it was causing issues with other projects. The real culprit here is the way that `wmic` handles quotes.. they do their own handling due to the complex queries it supports.

Anyway, you actually don't need to use `cross-spawn` because you are targeting a Windows ONLY command. Having that said I've added a new options for this:

```
const cp = buffspawn('wmic', ['logicaldisk', 'where', 'DeviceID="Z:"', 'get' 'freeSpace,size'], { crossSpawn: false }, () => {}};
```

Please update your code NOW TO include the `crossSpawn: false` option. Since I will revert the changes in cross-spawn, your code will break.
